name: etoile
description: "Etoile - Application de recrutement par video de 60 secondes"
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.10.8

dependencies:
  flutter:
    sdk: flutter

  # UI
  cupertino_icons: ^1.0.8
  flutter_svg: ^2.0.10+1
  cached_network_image: ^3.3.1
  shimmer: ^3.0.0
  google_fonts: ^6.2.1

  # State Management
  flutter_bloc: ^8.1.6
  equatable: ^2.0.5

  # Navigation
  go_router: ^14.6.2

  # Network
  dio: ^5.7.0
  connectivity_plus: ^6.1.0

  # Backend
  supabase_flutter: ^2.8.1

  # Local Storage
  hive_flutter: ^1.1.0
  shared_preferences: ^2.3.3

  # Video & Camera
  video_player: ^2.9.2
  chewie: ^1.8.5
  camera: ^0.11.0+2
  video_thumbnail: ^0.5.3
  image_picker: ^1.1.2
  crop_your_image: ^1.1.0

  # Map
  flutter_map: ^7.0.2
  latlong2: ^0.9.1
  geolocator: ^13.0.2

  # File system
  path_provider: ^2.1.4
  path: ^1.9.0

  # Utils
  dartz: ^0.10.1
  get_it: ^8.0.2
  injectable: ^2.5.0
  uuid: ^4.5.1
  intl: ^0.19.0
  url_launcher: ^6.3.1
  flutter_dotenv: ^5.1.0

  # OAuth social
  google_sign_in: ^6.2.1
  sign_in_with_apple: ^6.1.0

  # Push Notifications & Monitoring
  firebase_core: ^3.12.1
  firebase_crashlytics: ^4.3.3
  firebase_messaging: ^15.2.4
  flutter_local_notifications: ^18.0.1
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  build_runner: ^2.4.13
  injectable_generator: ^2.6.2
  hive_generator: ^2.0.1
  mocktail: ^1.0.4
  bloc_test: ^9.1.7
  flutter_launcher_icons: ^0.14.3

flutter_launcher_icons:
  android: true
  ios: true
  remove_alpha_ios: true
  image_path: "assets/icon/app_icon.png"
  adaptive_icon_background: "#333333"
  adaptive_icon_foreground: "assets/icon/app_icon.png"
  web:
    generate: true
    image_path: "assets/icon/app_icon.png"
  windows:
    generate: true
    image_path: "assets/icon/app_icon.png"

flutter:
  uses-material-design: true

  assets:
    - .env
    - assets/icon/
    - assets/images/
    - images/etoile/

  fonts:
    - family: Inter
      fonts:
        - asset: assets/fonts/Inter-Regular.ttf
          weight: 400
        - asset: assets/fonts/Inter-Medium.ttf
          weight: 500
        - asset: assets/fonts/Inter-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Inter-Bold.ttf
          weight: 700
